**Numpy**

Agenda:


1.What is NumPy?

2.Why Use NumPy?

3.Numpy Operations



**What is Numpy?**

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

**Why Use NumPy**

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

In [1]:
#Demo on list vs numpy interms of space
# Import sys module to measure memory usage
import sys

# Import NumPy library
import numpy as np

# Create a Python list containing 1 million integers
lst = list(range(1000000))

# Create a NumPy array containing 1 million integers
arr = np.arange(1000000)

# Get memory occupied by the list object
# Note: This does not include memory used by individual integer objects
print("List Size:", sys.getsizeof(lst), "bytes")

# Get actual memory occupied by NumPy array data
print("NumPy Array Size:", arr.nbytes, "bytes")


List Size: 8000056 bytes
NumPy Array Size: 8000000 bytes


In [2]:
#Demo to check speed in List
# Import time module to measure execution time
import time

# Create a list with 1 million numbers
lst = list(range(1000000))

# Record start time
start = time.time()

# Add 10 to every element using list comprehension
result = [x + 10 for x in lst]

# Record end time
end = time.time()

# Calculate execution time
print("List Time:", end - start, "seconds")

List Time: 0.06585526466369629 seconds


In [3]:
#Demo to check speed in Numpy
# Import NumPy and time modules
import numpy as np
import time

# Create NumPy array with 1 million numbers
arr = np.arange(1000000)

# Record start time
start = time.time()

# Vectorized operation
# NumPy internally performs this in optimized C code
result = arr + 10

# Record end time
end = time.time()

# Calculate execution time
print("NumPy Time:", end - start, "seconds")


NumPy Time: 0.07451319694519043 seconds


**Why is NumPy faster than Python Lists?**

NumPy stores data in contiguous memory locations.

All elements have the same data type.

Operations are implemented in optimized C code.

NumPy uses vectorization, avoiding Python loops.

Better CPU cache utilization.

**Why does NumPy use less memory?**

Python lists store references to objects.

Each integer in a list is a separate Python object.

NumPy stores raw values directly in memory.

Fixed data types reduce overhead.

**Array Operations**

Creating array NumPy is used to work with arrays. The array object in NumPy is called ndarray.
We can create a NumPy ndarray object by using the array() function.

1-D Arrays An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
These are the most common and basic arrays.

2-D Arrays An array that has 1-D arrays as its elements is called a 2-D array.
These are often used to represent matrix or 2nd order tensors.

3-D arrays An array that has 2-D arrays (matrices) as its elements is called 3-D array.
These are often used to represent a 3rd order tensor.

In [4]:
#Demo for types of array
import numpy as np

arr=np.array([10,20,30,40]) #1D
print(arr)

ar=np.array([[10,20,30],
     [40,50,60]])
print(ar)



[10 20 30 40]
[[10 20 30]
 [40 50 60]]


Check Number of Dimensions?

NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [5]:
#Demo for ndim
import numpy as np
ar=np.array([[1,2,3,4],[3,4,5,6]])
print(ar.ndim)

2


**NumPy Array Indexing**

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [6]:
#Demo for Indexing
import numpy as np
ar=np.array([1,2,3,4])
print(ar[2])

3


**Reshape**

Changes the shape (dimensions) of an array without changing its data.

Syntax: array.reshape(rows, columns)

In [7]:
#Demo for Reshape
import numpy as np
ar=np.array([1,2,3,4,3,4])
print(ar.reshape(2,3))

[[1 2 3]
 [4 3 4]]


**Slicing**

Extracting a portion of an array.

Syntax: array[start:end]

In [8]:
#Demo Slicing
import numpy as np
ar=np.array([1,2,3,4,3,4,5,6])
print(ar[1:6])

[2 3 4 3 4]


**Filtering**

Selects elements that satisfy a condition.

Syntax: array[condition] --> a(a>25) --> a is array

In [9]:
#Demo for filtering
import numpy as np
ar=np.array([1,2,30,49,39,89,5,6])
print(ar[ar>25])

[30 49 39 89]


**Creating a Range of Values:**

np.arange() generates a NumPy array containing evenly spaced values from start to stop (excluding stop) with the specified step size.

Syntax: np.arange(start, stop, step)

**Array of Zeros**

Creates an array filled with zeros.

Syntax: np.zeros(shape)

**Practice Questions:**

1.Create a NumPy array containing numbers from 1 to 20 using arange().

2.Create an array of all zeros with 10 elements.

3.Create an array of all ones with 8 elements.

4.Create an array containing even numbers from 2 to 20.

5.Create an array and Find:Number of dimensions, Shape, Size, Data type

6.Multiply every element by 2.

7.Find the square of every element.

8.Divide every element by 10.

9.Create 1D array and Find: Sum, Mean, Maximum, Minimum

10.Create 2 arrays and Concatenate both arrays.

In [10]:
#Create a numpy array containing numbers from 1 to 20 using arrange()
import numpy as np
arr1 = np.arange(1, 21)
print("Array from 1 to 20:")
print(arr1)

Array from 1 to 20:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [11]:
#Create an array of all zeros with 10 elements
zeros_arr = np.zeros(10)
print("Array of zeros:")
print(zeros_arr)

Array of zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
#Create an array of all ones with 8 elements
ones_arr = np.ones(8)
print("Array of ones:")
print(ones_arr)

Array of ones:
[1. 1. 1. 1. 1. 1. 1. 1.]


In [13]:
#Create an array containing even numbers from 2 to 20
even_arr = np.arange(2, 21, 2)
print("Even numbers from 2 to 20:")
print(even_arr)


Even numbers from 2 to 20:
[ 2  4  6  8 10 12 14 16 18 20]


In [14]:
#Create an array and Find : Number of dimensions, Shape, Size, Data type
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
print("Array:")
print(arr2)
print("Number of Dimensions:", arr2.ndim)
print("Shape:", arr2.shape)
print("Size:", arr2.size)
print("Data Type:", arr2.dtype)


Array:
[[1 2 3]
 [4 5 6]]
Number of Dimensions: 2
Shape: (2, 3)
Size: 6
Data Type: int64


In [15]:
#Multiply every element by 2
multiplied = arr1 * 2
print("Array after multiplying by 2:")
print(multiplied)

Array after multiplying by 2:
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


In [16]:
#Find the square of every element.
squared = arr1 ** 2
print("Square of every element:")
print(squared)

Square of every element:
[  1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289 324
 361 400]


In [17]:
#Divide every element by 10
divided = arr1 / 10
print("Array after dividing by 10:")
print(divided)

Array after dividing by 10:
[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8
 1.9 2. ]


In [18]:
#Create 1D array and Find: Sum, Mean, Maximum, Minimum
arr3 = np.array([10, 20, 30, 40, 50])
print("1D Array:")
print(arr3)
print("Sum:", np.sum(arr3))
print("Mean:", np.mean(arr3))
print("Maximum:", np.max(arr3))
print("Minimum:", np.min(arr3))

1D Array:
[10 20 30 40 50]
Sum: 150
Mean: 30.0
Maximum: 50
Minimum: 10


In [19]:
#Create 2 arrays & concatenate both arrays.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

concatenated = np.concatenate((a, b))
print("Concatenated Array:")
print(concatenated)

Concatenated Array:
[1 2 3 4 5 6]
